// =============================================================================
// Fastify Server Factory — apps/ai-service/src/server.ts
// Exposes secured POST /dialogue with anti-stampede caching and LLM fallback.
// =============================================================================

import Fastify, { FastifyInstance } from "fastify";
import { config } from "./config.js";
import { getCachedDialogue, setCachedDialogue } from "./storage/redis.js";
import { inflightDeduplicator } from "./cache/stampede.js";
import { generateDialogue } from "./llm/client.js";

export type DialogueRequestBody = {
  contextHash: string;
  bucketedStats?: Record<string, unknown>;
  npcArchetype: string;
  fallbackLine: string;
  zoneType?: string;
};

export function buildApp(): FastifyInstance {
  const app = Fastify({
    logger: false,
  });

  // ---------------------------------------------------------------------------
  // GET /health — Liveness probe
  // ---------------------------------------------------------------------------
  app.get("/health", async (_req, reply) => {
    return reply.send({
      status: "ok",
      service: "ai-service",
      uptimeSec: Math.floor(process.uptime()),
      ts: Date.now(),
    });
  });

  // ---------------------------------------------------------------------------
  // POST /dialogue — Tiered AI dialogue generation
  // ---------------------------------------------------------------------------
  app.post<{ Body: DialogueRequestBody }>("/dialogue", async (req, reply) => {
    // 1. Security Header Enforcement: x-internal-key
    const internalKey = req.headers["x-internal-key"];
    if (internalKey !== config.internalApiKey) {
      return reply.status(401).send({
        error: "UNAUTHORIZED",
        message: "Invalid or missing x-internal-key header",
      });
    }

    const { contextHash, bucketedStats, npcArchetype, fallbackLine, zoneType } = req.body;

    if (!contextHash || !npcArchetype || fallbackLine === undefined) {
      return reply.status(400).send({
        error: "BAD_REQUEST",
        message: "contextHash, npcArchetype, and fallbackLine are required fields",
      });
    }

    // 2. Step 1: Redis Cache Check
    const cachedText = await getCachedDialogue(contextHash);
    if (cachedText) {
      return reply.send({
        text: cachedText,
        fromCache: true,
      });
    }

    // 3. Step 2: Anti-Stampede Deduplication on Cache Miss
    try {
      const { text, wasDeduplicated } = await inflightDeduplicator.execute(
        contextHash,
        async () => {
          // Inner execution: only ONE caller reaches this during concurrent miss window
          const result = await generateDialogue(
            npcArchetype,
            bucketedStats ?? {},
            fallbackLine,
            zoneType ?? "commercial"
          );

          // If successfully generated by LLM (not fallback), cache in Redis for 6 hours
          if (!result.fallback) {
            await setCachedDialogue(contextHash, result.text, config.cacheTtlSeconds);
          }

          return result.text;
        }
      );

      return reply.send({
        text,
        fromCache: false,
        wasDeduplicated,
      });
    } catch (err) {
      // Guaranteed safety net fallback
      req.log?.warn?.(err, "Unhandled dialogue pipeline error");
      return reply.send({
        text: fallbackLine,
        fromCache: false,
        fallback: true,
      });
    }
  });

  return app;
}
